# Generated by GPT-5.2 on 2026-04-29

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_default_users(apps, schema_editor):
    User = apps.get_model("api", "User")
    StudentProfile = apps.get_model("api", "StudentProfile")
    DoctorProfile = apps.get_model("api", "DoctorProfile")
    MedicineItem = apps.get_model("api", "MedicineItem")
    Inventory = apps.get_model("api", "Inventory")

    def upsert_user(*, email, password, full_name, phone, department, role):
        user, created = User.objects.get_or_create(
            email=email,
            defaults={
                "username": email,
                "full_name": full_name,
                "phone": phone,
                "department": department,
                "role": role,
            },
        )
        changed = created
        for field, value in [
            ("username", email),
            ("full_name", full_name),
            ("phone", phone),
            ("department", department),
            ("role", role),
        ]:
            if getattr(user, field, None) != value:
                setattr(user, field, value)
                changed = True

        # In migrations, the historical model doesn't reliably expose `set_password`.
        # Use `make_password` to store a correct hash.
        hashed = make_password(password)
        if getattr(user, "password", None) != hashed:
            user.password = hashed
            changed = True

        if changed:
            user.save()
        return user

    admin = upsert_user(
        email="admin@gmail.com",
        password="Admin@123",
        full_name="System Admin",
        phone="9000000001",
        department="Administration",
        role="admin",
    )
    doctor = upsert_user(
        email="doctor@gmail.com",
        password="Doctor@123",
        full_name="Dr. Priya Sharma",
        phone="9000000002",
        department="Medical Unit",
        role="doctor",
    )
    student = upsert_user(
        email="student@gmail.com",
        password="Student@123",
        full_name="Rahul Kumar",
        phone="9000000003",
        department="CSE",
        role="student",
    )
    pharmacist = upsert_user(
        email="pharma@gmail.com",
        password="Pharma@123",
        full_name="Amit Verma",
        phone="9000000004",
        department="Pharmacy",
        role="pharmacist",
    )

    StudentProfile.objects.get_or_create(
        user=student,
        defaults={
            "enrollment_no": "CSE2026001",
            "semester": "6",
            "course": "B.Tech CSE",
        },
    )
    DoctorProfile.objects.get_or_create(
        user=doctor,
        defaults={
            "specialization": "General Medicine",
            "license_no": "LIC-2026-DR-1001",
            "years_of_experience": 2,
        },
    )

    med, _ = MedicineItem.objects.get_or_create(name="Paracetamol", defaults={"stock": 180})
    Inventory.objects.get_or_create(
        medicine=med,
        defaults={
            "reorder_level": 30,
            "last_updated_by": pharmacist,
        },
    )

    # Ensure admin is staff so Django admin works in dev if needed.
    if not admin.is_staff:
        admin.is_staff = True
        admin.is_superuser = True
        admin.save(update_fields=["is_staff", "is_superuser"])


def noop_reverse(apps, schema_editor):
    # Keep seeded demo accounts for development stability.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_appointment_doctor_appointment_student_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_users, reverse_code=noop_reverse),
    ]

