# Generated by Django 4.2.7 on 2026-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_default_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
